### ISSUE TITLE
Package Versions for Reproducibility

### ISSUE THREAD

**Issue by Caiofcas** [hahhcc/ACP-DL#1]
Hello, I'm a student in Brazil and find the paper that produced this tool super interesting! 

I attempted to run the code provided to reproduce the results but couldn't due to the following error:

```
$ python ACP_DL.py

Traceback (most recent call last):
  File "ACP_DL.py", line 2, in <module>
    from keras.layers import LSTM, Dense, Dropout, Activation, initializers, GRU, SimpleRNN
ImportError: cannot import name 'initializers' from 'keras.layers' (/home/caio/.local/lib/python3.8/site-packages/keras/layers/__init__.py)
```

I think this is probably a package version issue, where the module initializers changed name, but I couldn't find the version used in the code, could you possibly provide a `requirements.txt` file so that the findings are more easily reproduced ? (https://www.idkrtm.com/what-is-the-python-requirements-txt/)

I have the following:
```
$ python --version

Python 3.8.5

$ pip freeze | grep Keras

Keras==2.4.3
Keras-Preprocessing==1.1.2

$ pip freeze | grep tensorflow

tensorflow==2.3.0
tensorflow-estimator==2.3.0
```

Any help would be appreciated!

**Comment by haichengyi** [comment]
My Keras is 2.0.8 and Tensorflow is 1.12.0 . And it seems that initializers is not used by the code, you can comment it out.

**Comment by Caiofcas** [comment]
Thank you!! Now it works perfectly.
